# -*- encoding: utf-8 -*-
{
    "name": "Construction Management Theme",
    'description': 'Construction Management Theme',
    'version': '15.0.0.1',
    'category': 'Theme/Construction',
    'author': 'Jupical Technologies Pvt. Ltd.',
    'maintainer': 'Jupical Technologies Pvt. Ltd.',
    "website": "www.jupical.com",
    "depends": ['website','crm','website_blog'],
    'data': [
            'template/assets.xml',
            'template/layout.xml',
            'template/home_page.xml',
            'template/about_page.xml',
            'template/project_page.xml',
            'template/contact_page.xml',
            'template/snippets.xml',
    ],
    'images': [
        'static/description/bg_1.jpg',
        'static/description/bg_2.jpg',],
    'assets':{'theme_ht_construction.assets_wysiwyg':[
                                        '/theme_ht_construction/static/src/css/open-iconic-bootstrap.min.css',
                                        '/theme_ht_construction/static/src/css/animate.css',
                                        '/theme_ht_construction/static/src/css/owl.carousel.min.css',
                                        '/theme_ht_construction/static/src/css/owl.theme.default.min.css',
                                        '/theme_ht_construction/static/src/css/magnific-popup.css',
                                        '/theme_ht_construction/static/src/css/aos.css',
                                        '/theme_ht_construction/static/src/css/ionicons.min.css',
                                        '/theme_ht_construction/static/src/css/bootstrap-datepicker.css',
                                        '/theme_ht_construction/static/src/css/jquery.timepicker.css',
                                        '/theme_ht_construction/static/src/css/flaticon.css',
                                        '/theme_ht_construction/static/src/css/icomoon.css',
                                        '/theme_ht_construction/static/src/css/style.css',
                                        'theme_ht_construction/static/src/js/jquery-migrate-3.0.1.min.js',
                                        'theme_ht_construction/static/src/js/popper.min.js',
                                        'theme_ht_construction/static/src/js/bootstrap.min.js',
                                        'theme_ht_construction/static/src/js/jquery.easing.1.3.js',
                                        'theme_ht_construction/static/src/js/jquery.waypoints.min.js',
                                        'theme_ht_construction/static/src/js/jquery.stellar.min.js',
                                        'theme_ht_construction/static/src/js/owl.carousel.min.js',
                                        'theme_ht_construction/static/src/js/jquery.magnific-popup.min.js',
                                        'theme_ht_construction/static/src/js/aos.js',
                                        'theme_ht_construction/static/src/js/jquery.animateNumber.min.js',
                                        'theme_ht_construction/static/src/js/bootstrap-datepicker.js',
                                        'theme_ht_construction/static/src/js/jquery.timepicker.min.js',
                                        'theme_ht_construction/static/src/js/scrollax.min.js',
                                        'theme_ht_construction/static/src/js/main.js'
                                        ]
    },
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
