{
    "name": "Construction Theme",
    "summary": "Webiste Construction Theme",
    'description': 'Webiste Construction Theme',
    'version': '15.0.0.1',
    'category': 'Theme/Construction',
    'author': 'Jupical Technologies Pvt. Ltd.',
    'maintainer': 'Jupical Technologies Pvt. Ltd.',
    'contributors':['Anil Kesariya <anil.r.kesariya@gmail.com>'],
    "webiste": "www.jupical.com",

    "depends": ['website','crm','website_crm','website_blog'],
    'data': [
            'template/assets.xml',
            'template/layout.xml',
            'template/home_page.xml',
            'template/about_page.xml',
            'template/career_page.xml',
            'template/history_page.xml',
            'template/partnerships_page.xml',
            'template/leadership_page.xml',
            'template/services_page.xml',
            'template/services_details_page.xml',
            'template/project_page.xml',
            'template/project_details_page.xml',
            'template/blog_page.xml',
            'template/faq_page.xml',
            'template/testimonial_page.xml',
            'template/contact_page.xml',
            'template/login_page.xml',
            'template/register_page.xml',
            'template/snippet.xml',
            'template/contact_thank_you.xml',
    ],
    'images': [
        'static/description/banner_3.jpg',
        'static/description/banner_3.jpg',],
    'assets':{'theme_jt_construction.assets_wysiwyg':[
                                        '/theme_jt_construction/static/src/assets/css/bootstrap.min.css',
                                        '/theme_jt_construction/static/src/assets/css/owl.carousel.css',
                                        '/theme_jt_construction/static/src/assets/css/font-awesome.css',
                                        '/theme_jt_construction/static/src/assets/css/ionicons.css',
                                        '/theme_jt_construction/static/src/assets/css/flaticon.css',
                                        '/theme_jt_construction/static/src/assets/css/simple-line-icons.css',
                                        '/theme_jt_construction/static/src/assets/css/animate.css',
                                        '/theme_jt_construction/static/src/assets/css/jquery-ui.min.css',
                                        '/theme_jt_construction/static/src/assets/css/settings.css',
                                        '/theme_jt_construction/static/src/assets/css/layers.css',
                                        '/theme_jt_construction/static/src/assets/css/style.css',
                                        '/theme_jt_construction/static/src/assets/css/index.css',
                                        '/theme_jt_construction/static/src/assets/css/header.css',
                                        '/theme_jt_construction/static/src/assets/css/footer.css',
                                        '/theme_jt_construction/static/src/assets/css/theme-color/default.css',
                                        '/theme_jt_construction/static/src/assets/js/imagesloaded.pkgd.min.js',
                                        '/theme_jt_construction/static/src/assets/js/isotope.pkgd.min.js',
                                        '/theme_jt_construction/static/src/assets/js/masonry.pkgd.min.js',
                                        '/theme_jt_construction/static/src/assets/js/jquery.appear.js',
                                        '/theme_jt_construction/static/src/assets/js/owl.carousel.js',
                                        '/theme_jt_construction/static/src/assets/js/custom.js',
                                        '/theme_jt_construction/static/src/assets/js/jquery.fancybox.pack.js',
                                        '/theme_jt_construction/static/src/assets/js/jquery.themepunch.tools.min.js',
                                        '/theme_jt_construction/static/src/assets/js/jquery.themepunch.revolution.min.js',
                                        '/theme_jt_construction/static/src/assets/extensions/revolution.extension.slideanims.min.js',
                                        '/theme_jt_construction/static/src/assets/extensions/revolution.extension.layeranimation.min.js',
                                        '/theme_jt_construction/static/src/assets/extensions/revolution.extension.navigation.min.js',
                                        '/theme_jt_construction/static/src/assets/extensions/revolution.extension.parallax.min.js',
                                        '/theme_jt_construction/static/src/assets/js/jquery.revolution.js'
                                        ]
    },
    'installable': True,
    'auto_install': False,

}
