# -*- encoding: utf-8 -*-
{
    'name': "Salon Management Theme",
    'description': 'Salon Management Theme',
    'category': 'Theme/Salon',
    'version': '15.0.0.1',
    'author': 'Jupical Technologies Pvt. Ltd.',
    'depends': ['website','crm','website_blog'],
    'data': [
            'template/assets.xml',
            'template/layout.xml',
            'template/home_page.xml',
            'template/about_page.xml',
            'template/services_page.xml',
            'template/barbershop_page.xml',
            'template/contact_page.xml',
            'template/thank_you.xml',
            'template/snippets.xml',
    ],
    'images': [
        'static/description/hero_1.jpg',
        'static/description/hero_2.jpg',],
    'assets':{'theme_jt_salon.assets_wysiwyg':[
                                        '/theme_jt_salon/static/src/fonts/icomoon/style.css',
                                        '/theme_jt_salon/static/src/css/bootstrap.min.css',
                                        '/theme_jt_salon/static/src/css/bootstrap-datepicker.css',
                                        '/theme_jt_salon/static/src/css/jquery.fancybox.min.css',
                                        '/theme_jt_salon/static/src/css/owl.carousel.min.css',
                                        '/theme_jt_salon/static/src/css/owl.theme.default.min.css',
                                        '/theme_jt_salon/static/src/fonts/flaticon/font/flaticon.css',
                                        '/theme_jt_salon/static/src/css/aos.css',
                                        '/theme_jt_salon/static/src/css/style.css',
                                        '/theme_jt_salon/static/src/js/jquery-migrate-3.0.1.min.js',
                                        '/theme_jt_salon/static/src/js/popper.min.js',
                                        '/theme_jt_salon/static/src/js/bootstrap.min.js',
                                        '/theme_jt_salon/static/src/js/owl.carousel.min.js',
                                        '/theme_jt_salon/static/src/js/jquery.sticky.js',
                                        '/theme_jt_salon/static/src/js/jquery.waypoints.min.js',
                                        '/theme_jt_salon/static/src/js/jquery.animateNumber.min.js',
                                        '/theme_jt_salon/static/src/js/jquery.fancybox.min.js',
                                        '/theme_jt_salon/static/src/js/jquery.stellar.min.js',
                                        '/theme_jt_salon/static/src/js/jquery.easing.1.3.js',
                                        '/theme_jt_salon/static/src/js/bootstrap-datepicker.min.js',
                                        '/theme_jt_salon/static/src/js/aos.js',
                                        '/theme_jt_salon/static/src/js/main.js'
                                        ]
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}