{
    "name": "Salon Management Theme",
    "summary": "Jupical Salon Theme",
    'description': '',
    'version': '14.0.0.1',
    'category': 'Theme/Salon',
    'author': 'Jupical Technologies Pvt. Ltd.',
    'maintainer': 'Jupical Technologies Pvt. Ltd.',
    "website": "www.jupical.com",
    "depends": ['website','crm','website_form','website_blog'],
    'data': [
            'template/assets.xml',
            'template/layout.xml',
            'template/home_page.xml',
            'template/about_page.xml',
            'template/services_page.xml',
            'template/barbershop_page.xml',
            'template/contact_page.xml',
            'template/thank_you.xml',
            'template/snippets.xml',
    ],
    'installable': True,
    'auto_install': False,

}
