{
    'name': 'Gym Management Theme',
    'summary': 'Webiste Gym Management Theme',
    'description': '',
    'version': '15.0.0.1',
    'category': 'Theme/Gym',
    'author': 'Jupical Technology',
    'webiste': 'www.jupical.com',
    'depends': ['website','crm','website_crm','website_blog'],
    'data': [
            'template/assets.xml',
            'template/layout.xml',
            'template/home_page.xml',
            'template/about_page.xml',
            'template/class_details_page.xml',
            'template/services_page.xml',
            'template/team_page.xml',
            'template/bmi_calculator_page.xml',
            'template/gallery_page.xml',
            'template/blog_page.xml',
            'template/contact_page.xml',
            'template/blog_details_page.xml',
            'template/snippets.xml',
            'template/contact_thank_you_page.xml',
    ],
    'images': [
        'static/description/1.jpg',
        'static/description/1.jpg',],
    'assets':{'theme_jt_gym.assets_wysiwyg':[
                                        '/theme_jt_gym/static/src/css/bootstrap.min.css',
                                        '/theme_jt_gym/static/src/css/font-awesome.min.css',
                                        '/theme_jt_gym/static/src/css/flaticon.css',
                                        '/theme_jt_gym/static/src/css/owl.carousel.min.css',
                                        '/theme_jt_gym/static/src/css/barfiller.css',
                                        '/theme_jt_gym/static/src/css/magnific-popup.css',
                                        '/theme_jt_gym/static/src/css/slicknav.min.css',
                                        '/theme_jt_gym/static/src/css/style.css',
                                        '/theme_jt_gym/static/src/js/bootstrap.min.js',
                                        '/theme_jt_gym/static/src/js/jquery.magnific-popup.min.js',
                                        '/theme_jt_gym/static/src/js/masonry.pkgd.min.js',
                                        '/theme_jt_gym/static/src/js/jquery.barfiller.js',
                                        '/theme_jt_gym/static/src/js/jquery.slicknav.js',
                                        '/theme_jt_gym/static/src/js/owl.carousel.min.js',
                                        '/theme_jt_gym/static/src/js/main.js'
                                        ]
    },
    'installable': True,
    'auto_install': False,

}
