{
    'name': 'Gym Management Theme',
    'summary': 'Webiste Gym Management Theme',
    'description': '',
    'version': '14.0.0.1',
    'category': 'Theme/Gym',
    'author': 'Jupical Technology',
    'webiste': 'www.jupical.com',
    'depends': ['website','crm','website_crm','website_blog'],
    'data': [
            'template/assets.xml',
            'template/layout.xml',
            'template/home_page.xml',
            'template/about_page.xml',
            'template/class_details_page.xml',
            'template/services_page.xml',
            'template/team_page.xml',
            'template/bmi_calculator_page.xml',
            'template/gallery_page.xml',
            'template/blog_page.xml',
            'template/contact_page.xml',
            'template/blog_details_page.xml',
            'template/snippets.xml',
            'template/contact_thank_you_page.xml',
    ],
    'installable': True,
    'auto_install': False,

}
