{
    "name": "Gym Theme Management",
    "summary": "Jupical Website Theme",
    'description': '',
    'version': '14.0.0.1',
    'category': 'Theme/Gym',
    'author': 'Jupical Technologies Pvt. Ltd.',
    'maintainer': 'Jupical Technologies Pvt. Ltd.',
    "website": "www.jupical.com",
    "depends": ['website','crm','website_form','website_blog'],
    'data': [
            'template/assets.xml',
            'template/layout.xml',
            'template/home_page.xml',
            'template/about_page.xml',
            'template/pricing_page.xml',
            'template/gallery_page.xml',
            'template/contact_page.xml',
            'template/snippets.xml',
            'template/thank_you.xml',
    ],
    'installable': True,
    'auto_install': False,

}
