# -*- encoding: utf-8 -*-
{
    "name": "Gym Theme Management",
    'description': 'Gym Management',
    'version': '15.0.0.1',
    'category': 'Theme/Gym',
    'author': 'Jupical Technologies Pvt. Ltd.',
    'maintainer': 'Jupical Technologies Pvt. Ltd.',
    "website": "www.jupical.com",
    "depends": ['website','crm','website_blog'],
    'data': [
            'template/assets.xml',
            'template/layout.xml',
            'template/home_page.xml',
            'template/about_page.xml',
            'template/pricing_page.xml',
            'template/gallery_page.xml',
            'template/contact_page.xml',
            'template/snippets.xml',
            'template/thank_you.xml',
    ],
    'images': [
        'static/description/about_1.png',
        'static/description/about_2.png',],
    'assets':{'theme_ht_gym.assets_wysiwyg':[
                                        '/theme_ht_gym/static/src/css/bootstrap.min.css',
                                        '/theme_ht_gym/static/src/css/owl.carousel.min.css',
                                        '/theme_ht_gym/static/src/css/magnific-popup.css',
                                        '/theme_ht_gym/static/src/css/font-awesome.min.css',
                                        '/theme_ht_gym/static/src/css/themify-icons.css',
                                        '/theme_ht_gym/static/src/css/gijgo.css',
                                        '/theme_ht_gym/static/src/css/nice-select.css',
                                        '/theme_ht_gym/static/src/css/flaticon.css',
                                        '/theme_ht_gym/static/src/css/slicknav.css',
                                        '/theme_ht_gym/static/src/css/style.css',
                                        '/theme_ht_gym/static/src/js/jquery-migrate-3.0.1.min.js',
                                        '/theme_ht_gym/static/src/js/vendor/modernizr-3.5.0.min.js',
                                        '/theme_ht_gym/static/src/js/popper.min.js',
                                        '/theme_ht_gym/static/src/js/bootstrap.min.js',
                                        '/theme_ht_gym/static/src/js/owl.carousel.min.js',
                                        '/theme_ht_gym/static/src/js/isotope.pkgd.min.js',
                                        '/theme_ht_gym/static/src/js/ajax-form.js',
                                        '/theme_ht_gym/static/src/js/waypoints.min.js',
                                        '/theme_ht_gym/static/src/js/jquery.counterup.min.js',
                                        '/theme_ht_gym/static/src/js/imagesloaded.pkgd.min.js',
                                        '/theme_ht_gym/static/src/js/scrollIt.js',
                                        '/theme_ht_gym/static/src/js/jquery.scrollUp.min.js',
                                        '/theme_ht_gym/static/src/js/wow.min.js',
                                        '/theme_ht_gym/static/src/js/nice-select.min.js',
                                        '/theme_ht_gym/static/src/js/jquery.slicknav.min.js',
                                        '/theme_ht_gym/static/src/js/jquery.magnific-popup.min.js',
                                        '/theme_ht_gym/static/src/js/plugins.js',
                                        '/theme_ht_gym/static/src/js/contact.js',
                                        '/theme_ht_gym/static/src/js/jquery.ajaxchimp.min.js',
                                        '/theme_ht_gym/static/src/js/jquery.form.js',
                                        '/theme_ht_gym/static/src/js/jquery.validate.min.js',
                                        '/theme_ht_gym/static/src/js/mail-script.js',
                                        '/theme_ht_gym/static/src/js/main.js'
                                        ]
    },
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',

}
