# -*- coding: utf-8 -*-
{
    "name": "Loan Theme Management",
    "summary": "Loan Website Theme",
    'description': '',
    'version': '15.0.0.1',
    'category': 'Theme/Loan',
    'author': 'Harhu Technologies Pvt. Ltd.',
    'maintainer': 'Harhu Technologies Pvt. Ltd.',
    "website": "www.harhu.com",
    "depends": ['website','crm','website_blog','website_crm'],
    'data': [
            'template/layout.xml',
            'template/home_page.xml',
            'template/about_page.xml',
            'template/services_page.xml',
            'template/contact_page.xml',
            'template/thank_you.xml',
            'template/snippets.xml',
    ],
    'images': [
        'static/src/assets/img/hero/hero_img.jpg',
        'static/src/assets/img/hero/hero_img.jpg',],
    'assets': {'web.assets_frontend':
                                ['/theme_ht_loan/static/src/assets/css/bootstrap.min.css',
                                '/theme_ht_loan/static/src/assets/css/owl.carousel.min.css',
                                '/theme_ht_loan/static/src/assets/css/slicknav.css',
                                '/theme_ht_loan/static/src/assets/css/flaticon.css',
                                '/theme_ht_loan/static/src/assets/css/animate.min.css',
                                '/theme_ht_loan/static/src/assets/css/magnific-popup.css',
                                '/theme_ht_loan/static/src/assets/css/fontawesome-all.min.css',
                                '/theme_ht_loan/static/src/assets/css/themify-icons.css',
                                '/theme_ht_loan/static/src/assets/css/slick.css',
                                '/theme_ht_loan/static/src/assets/css/nice-select.css',
                                '/theme_ht_loan/static/src/assets/css/style.css',
                                '/theme_ht_loan/static/src/assets/js/jquery-migrate-3.0.1.min.js',
                                '/theme_ht_loan/static/src/assets/js/vendor/modernizr-3.5.0.min.js',
                                '/theme_ht_loan/static/src/assets/js/popper.min.js',
                                '/theme_ht_loan/static/src/assets/js/bootstrap.min.js',
                                '/theme_ht_loan/static/src/assets/js/jquery.slicknav.min.js',
                                '/theme_ht_loan/static/src/assets/js/owl.carousel.min.js',
                                '/theme_ht_loan/static/src/assets/js/slick.min.js',
                                '/theme_ht_loan/static/src/assets/js/wow.min.js',
                                '/theme_ht_loan/static/src/assets/js/animated.headline.js',
                                '/theme_ht_loan/static/src/assets/js/jquery.magnific-popup.js',
                                '/theme_ht_loan/static/src/assets/js/jquery.nice-select.min.js',
                                '/theme_ht_loan/static/src/assets/js/jquery.sticky.js',
                                '/theme_ht_loan/static/src/assets/js/contact.js',
                                '/theme_ht_loan/static/src/assets/js/jquery.form.js',
                                '/theme_ht_loan/static/src/assets/js/jquery.validate.min.js',
                                '/theme_ht_loan/static/src/assets/js/mail-script.js',
                                '/theme_ht_loan/static/src/assets/js/jquery.ajaxchimp.min.js',
                                '/theme_ht_loan/static/src/assets/js/plugins.js',
                                '/theme_ht_loan/static/src/assets/js/main.js'
                                ]
    },
    'installable': True,
    'auto_install': False,

}
